### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by wongee93** [wongee93/TodoProject2#1]
### 만들고자 하는 기능

- [x]  Todo 생성 기능
- [x]  Todo 삭제 기능
- [ ]  Todo 수정 기능
